#!/usr/bin/env python3
"""
Generate release notes from merged PRs since last tag.

Usage:
    python scripts/generate-release-notes.py              # Since last tag
    python scripts/generate-release-notes.py v2.0.0       # Since specific tag
    python scripts/generate-release-notes.py --latest 5   # Last 5 PRs
"""

import subprocess
import sys
import re
from datetime import datetime
from collections import defaultdict

CATEGORIES = {
    "feat": "🚀 Features",
    "fix": "🐛 Bug Fixes",
    "docs": "📚 Documentation",
    "refactor": "🔧 Refactoring",
    "test": "✅ Tests",
    "chore": "🧹 Chores",
    "perf": "⚡ Performance",
    "style": "💄 Style",
    "ci": "👷 CI/CD",
}


def get_prs_since(tag: str | None, limit: int | None = None) -> list[dict]:
    """Get merged PRs since the given tag, or latest N PRs."""
    if limit:
        cmd = ["gh", "pr", "list", "--state", "merged", "--limit", str(limit),
               "--json", "number,title,author,mergedAt,labels"]
    elif tag:
        cmd = ["gh", "pr", "list", "--state", "merged", "--search",
               f"base:main merged:>{tag}", "--json",
               "number,title,author,mergedAt,labels"]
    else:
        # Get latest tag
        try:
            result = subprocess.run(
                ["git", "describe", "--tags", "--abbrev=0"],
                capture_output=True, text=True
            )
            last_tag = result.stdout.strip()
        except Exception:
            last_tag = "v0.0.0"

        cmd = ["gh", "pr", "list", "--state", "merged", "--search",
               f"base:main merged:>{last_tag}", "--json",
               "number,title,author,mergedAt,labels"]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error fetching PRs: {result.stderr}", file=sys.stderr)
        return []

    import json
    return json.loads(result.stdout)


def categorize_pr(title: str) -> str:
    """Determine PR category from title conventional commit prefix."""
    match = re.match(r"^(\w+)(\(.*?\))?:", title)
    if match:
        prefix = match.group(1).lower()
        if prefix in CATEGORIES:
            return prefix
    return "other"


def generate_markdown(prs: list[dict], version: str | None = None) -> str:
    """Generate release notes markdown."""
    categorized = defaultdict(list)
    contributors = set()

    for pr in prs:
        cat = categorize_pr(pr["title"])
        categorized[cat].append(pr)
        if pr.get("author"):
            contributors.add(pr["author"]["login"])

    lines = []
    if version:
        lines.append(f"# {version}")
    lines.append(f"Released: {datetime.now().strftime('%Y-%m-%d')}")
    lines.append("")

    # Summary
    lines.append(f"## Summary")
    lines.append(f"- {len(prs)} merged PRs")
    lines.append(f"- {len(contributors)} contributors")
    lines.append("")

    # By category
    for prefix, heading in CATEGORIES.items():
        if prefix in categorized:
            lines.append(f"## {heading}")
            lines.append("")
            for pr in categorized[prefix]:
                title = pr["title"]
                # Strip conventional commit prefix for display
                display = re.sub(r"^\w+(\(.*?\))?:\s*", "", title)
                author = pr.get("author", {}).get("login", "unknown")
                pr_num = pr["number"]
                lines.append(f"- {display} (#{pr_num}) — @{author}")
            lines.append("")

    # Contributors
    if contributors:
        lines.append("## Contributors")
        for c in sorted(contributors):
            lines.append(f"- @{c}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by `scripts/generate-release-notes.py`*")

    return "\n".join(lines)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate release notes from merged PRs")
    parser.add_argument("tag", nargs="?", help="Tag to generate notes since")
    parser.add_argument("--latest", type=int, help="Include only latest N PRs")
    parser.add_argument("--version", help="Version string for heading")
    parser.add_argument("--output", "-o", help="Output file (default: stdout)")

    args = parser.parse_args()

    prs = get_prs_since(args.tag, args.latest)
    if not prs:
        print("No PRs found.", file=sys.stderr)
        sys.exit(1)

    markdown = generate_markdown(prs, args.version)

    if args.output:
        with open(args.output, "w") as f:
            f.write(markdown)
        print(f"Release notes written to {args.output}")
    else:
        print(markdown)
